version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Appraisal Install
          command: bundle exec appraisal install
      - run:
          name: Appraisal Run Tests
          command: bundle exec appraisal rspec
